# Course - Introduction to R 

##### NOTE: 
1. Your code MUST execute without any errors. 
2. You can add more lines in your code as required.

## Section 1: Data Types and Operations Pt. 1

### Question 1 
**Create the variables with the following composition:**
1. A vector containing each letter of your first name as its elements.
2. A variable that contains your name concatenated from the vector created in (1)
3. A variable containing a sequence from 100 to 120.
4. Create a matrix of 3x3 dimensions that contains the even sequence of numbers starting from 2.
5. Assign names to the variables.

In [ ]:
#### Start solution ####

In [2]:
myname <- c("z","u","l","a","i","k","h","a")
print(myname)

[1] "z" "u" "l" "a" "i" "k" "h" "a"


In [3]:
print(paste(myname , collapse=""))

[1] "zulaikha"


In [6]:
var_seq <- 100:120
var_seq

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120

In [7]:
mtrx_1 <- matrix(2:10, nrow=3, ncol=3)
mtrx_1

[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 3    6     9  
[3,] 4    7    10

In [12]:
dimnames(mtrx_1) <- list(c("Row1","Row2","Row3"),c("Column1","Column2","Column3"))
mtrx_1

Column1 Column2 Column3
Row1 2       5        8     
Row2 3       6        9     
Row3 4       7       10

In [ ]:
#### End solution ####

### Question 2
**Create a factor variable emp_status:**
1. Containing the categorical variables: Employed, Unemployed, Self-Employed, with each level appearing atleast more than 2.
2. Display the levels and the factor variable as a table.
3. Unclass the elements of the factor variable.

In [4]:
#### Start solution ####

In [13]:
cat_var <- factor(c("Employed","Employed","Un-Employed","Self-Employed","Employed","Un-Employed","Self-Employed"),levels = c("Employed","Un-Employed","Self-Employed"))
cat_var

[1] Employed      Employed      Un-Employed   Self-Employed Employed     
[6] Un-Employed   Self-Employed
Levels: Employed Un-Employed Self-Employed

In [14]:
table(cat_var)

cat_var
     Employed   Un-Employed Self-Employed 
            3             2             2 

In [15]:
unclass(cat_var)

[1] 1 1 2 3 1 2 3
attr(,"levels")
[1] "Employed"      "Un-Employed"   "Self-Employed"

In [3]:
#### End solution ####

### Question 3
**Create a dataframe object called bank_customers:**
1. the data frame will have three columns: CustomerID, hasAccount, totalBalance
2. Fill the data as follows
    a. Alicia does not have an account. She is here for inquiry 
    b. Nancy is here to check on her account balance of USD 10,000.
    c. Fernando is here to deposit USD 100 in his account which had no balance.
    d. Louis will withdraw all his money from the account that had USD 2,000. 
    e. Diane is here for information. 
3. For customers that do not have a value, use NA as placeholder.
4. Print the number of rows, columns and names for the data frame.

In [ ]:
#### Start solution ####

In [16]:
## 1. Create a data frame object called bank_customers :
bank_customers <- data.frame(CustomerID=c("Alicia","Nancy","Fernando","Louis","Diane"),hasAccount=c(FALSE,TRUE,TRUE,TRUE,FALSE),totalBalance=c(NA,10000,000.00,2000,NA))
bank_customers

CustomerID hasAccount totalBalance
1 Alicia     FALSE         NA       
2 Nancy       TRUE      10000       
3 Fernando    TRUE          0       
4 Louis       TRUE       2000       
5 Diane      FALSE         NA

In [17]:
## Print number of rows
nrow(bank_customers)

[1] 5

In [18]:
## Print number of columns
ncol(bank_customers)

[1] 3

In [19]:
## Print names 
names(bank_customers)

[1] "CustomerID"   "hasAccount"   "totalBalance"

In [2]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 2: Control Structures 

### Question 1
**Create a variable containing a sequence of numbers from 1 to 100:**
1. Iterate over the variables and print those numbers which are prime.

**Create a variable var with a value of 1:**
1. Create a while loop and increase the value of var at each iteration. 
2. When you reach the 10th prime number, terminate the loop and print the number.

In [5]:
#### Start solution ####

In [20]:
## Create a variable containing a sequence of numbers from 1 to 100:
v <- 1:100
print(v)

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100


In [21]:
## Iterate over the variables and print those numbers which are prime.
for(x in v){
  if(x==1){
    next
  } else if(x==2){
    x==2
  } else if(x%%2==0){
    next
  } else if(x==3){
    x==3
  } else if(x%%3==0){
    next
  } else if(x==5){
    x==5
  } else if(x%%5==0){
    next
  } else if(x==7){
    x==7
  } else if(x%%7==0){
    next
  }
    print(x)
}

[1] 2
[1] 3
[1] 5
[1] 7
[1] 11
[1] 13
[1] 17
[1] 19
[1] 23
[1] 29
[1] 31
[1] 37
[1] 41
[1] 43
[1] 47
[1] 53
[1] 59
[1] 61
[1] 67
[1] 71
[1] 73
[1] 79
[1] 83
[1] 89
[1] 97


In [22]:
# create a variable var with a value of 1:
count <- 0
goal <- 10
var <- 1
while(count<goal){
  var <- var+1
  isprime <- TRUE
  for(i in 2:(var%/%2)){
    if(var%%i==0 && var!=2 && var!=3){
      isprime <-FALSE
    }
  }
  if(isprime){
    count<-count+1
    print(paste("#",count,"prime number is",var,sep=" "))
  }
}

[1] "# 1 prime number is 2"
[1] "# 2 prime number is 3"
[1] "# 3 prime number is 5"
[1] "# 4 prime number is 7"
[1] "# 5 prime number is 11"
[1] "# 6 prime number is 13"
[1] "# 7 prime number is 17"
[1] "# 8 prime number is 19"
[1] "# 9 prime number is 23"
[1] "# 10 prime number is 29"


In [6]:
#### End solution ####

### Question 2
**Create a matrix of size 3x3 called mat_1:**
1. Iterate over all the values one by one and print the element as well as the position in the matrix (row, col)

In [9]:
#### Start solution ####

In [23]:
## Create a matrix of size 3x3 called mat_1:
mat_1 <- matrix(1:9,nrow = 3,ncol = 3)
mat_1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [24]:
## 1. Iterate over all the values one by one and print the element as well as the position in the matrix (row, col):
for(i in seq_len(nrow(mat_1))){
  for(j in seq_len(ncol(mat_1))){
    print(mat_1[i,j])
    print(which(mat_1==mat_1[i,j], arr.ind=TRUE))
  }
}

[1] 1
     row col
[1,]   1   1
[1] 4
     row col
[1,]   1   2
[1] 7
     row col
[1,]   1   3
[1] 2
     row col
[1,]   2   1
[1] 5
     row col
[1,]   2   2
[1] 8
     row col
[1,]   2   3
[1] 3
     row col
[1,]   3   1
[1] 6
     row col
[1,]   3   2
[1] 9
     row col
[1,]   3   3


In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 3: Functions

### Question 1
**Create a function called gcd that finds the greatest common divisor of two numbers a and b:**
1. a and b, should be taken as input.
2. The function must print the GCD as well as return it.
3. The output must be saved in a variable called answer.

In [9]:
#### Start solution ####

In [25]:
## Create a function called gcd that finds the greatest common divisor of two numbers a and b:
gcd <- function(a,b){
  if(b > a){
    min_num = b
  } 
  else {
    min_num = a
  }
  for(i in 1:min_num+1){
    if(a%%i==0 && b%%i==0)
      answer = i
  }
  return(answer)
}

In [26]:
# return answer
answer <- gcd(28,36)
answer

[1] 4

In [14]:
#### End solution ####

### Question 2
**Create a function called allConditionsMeet, that checks whether two expressions evaluate to true:**
1. a and b, should be taken as input.
2. the function should check if a and b, both conditions, evaluate to True.
3. The function must returns a boolean value.
4. Using a method, print the arguments that function takes.

In [9]:
#### Start solution ####

In [27]:
## Create a function called allConditionsMeet, that checks whether two expressions evaluate to true:

allConditionsMeet <- function(a,b){
  if(a==TRUE && b==TRUE){
    return(TRUE)
  } else {
    FALSE
  }
}

In [28]:
allConditionsMeet(TRUE,FALSE)

[1] FALSE

In [29]:
allConditionsMeet(TRUE,TRUE)

[1] TRUE

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 4: Vectorized Operations

### Question 1
**Create two matrices matrix_1 and matrix_2 of dimensions 2x3 and 3x2:**
1. Perform element-wise multiplication.
2. Perform matrix multipilcation. 

**Create a 2x2 matrix my_mat:**
1. Write a function to find the determinant of the matrix.

In [9]:
#### Start solution ####

In [30]:
## Create two matrices matrix_1 and matrix_2 of dimensions 2x3 and 3x2:
matrix_1 <- matrix(c(5,8,9,16,18,20) ,nrow = 2,ncol = 3)
matrix_2 <- matrix(rep(5,6),nrow = 3,ncol=2)

matrix_1

[,1] [,2] [,3]
[1,] 5     9   18  
[2,] 8    16   20

In [31]:
matrix_2

[,1] [,2]
[1,] 5    5   
[2,] 5    5   
[3,] 5    5

In [ ]:
## perform element wise multiplication:


# element wise matrix cannot be performed as both matrices are of different dimensions

In [32]:
## perform matrix multiplication :
matrix_1 %*% matrix_2

[,1] [,2]
[1,] 160  160 
[2,] 220  220

In [33]:
## create a 2x2 matrix my_mat:
my_mat <- matrix(c(2,4,6,8),nrow = 2,ncol = 2)

## Write a function to find the determinant of the matrix.
det_mat <- function(a){
  d <- det(a)
  return(d)
}

det_mat(my_mat)

[1] -8

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 5: Date and Time in R

### Question 1
**Use the current date and time and store them into variables curr_date and curr_time respectively: [use sys]**
1. Convert both into date and time objects using the appropriate functions.
2. Print the weekday, year, second and hour using the appropriate function and variables.

In [9]:
#### Start solution ####

In [34]:
## Use the current date and time and store them into variables curr_date and curr_time respectively: [use sys]
curr_date <- Sys.Date()
curr_date

[1] "2022-11-25"

In [35]:
curr_time <- Sys.time()
curr_time

[1] "2022-11-25 22:28:10 +03"

In [36]:
## Convert both into date and time objects using the appropriate functions.
d <- as.POSIXlt(curr_date)
d

[1] "2022-11-25 UTC"

In [37]:
t <- as.POSIXlt(curr_time)
t

[1] "2022-11-25 22:28:10 +03"

In [38]:
## Print the weekday, year, second and hour using the appropriate function and variables.
print(paste("weekday", t$wday))
print(paste("year :",t$year))
print(paste("seconds :",t$sec))
print(paste("hour :",t$hour))

[1] "weekday 5"
[1] "year : 122"
[1] "seconds : 10.4366519451141"
[1] "hour : 22"


In [14]:
#### End solution ####

### Question 2
**Create a variable to store current date/time**
1. Create another variable that stores and set the timezone as GMT-5
2. Find the difference between your current time and the GMT-5 timezone.

In [9]:
#### Start solution ####

In [39]:
## Create a variable to store current date/time
x <- as.POSIXlt((Sys.time()))
x

[1] "2022-11-25 22:29:20 +03"

In [40]:
## Create another variable that stores and set the timezone as GMT-5
y <- strptime("2022-09-28 18:33:02","%Y-%m-%d %H:%M:%S",tz="GMT")
y

[1] "2022-09-28 18:33:02 GMT"

In [41]:
## Find the difference between your current time and the GMT-5 timezone.
x - y

Time difference of 58.0391 days

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 6: Loop Functions

### Question 1
**Create a function to calculate mean and standard deviation of the provided data**
1. Create a sequence of numbers from 100 to 150 store in a variable called numbers.
1. Use lapply, sapply, apply and tapply to implement the functions on "numbers" [only on the second half of the sequence for tapply]

In [9]:
#### Start solution ####

In [42]:
## Create a sequence of numbers from 100 to 150 store in a variable called numbers.
numbers <- list(100:150)
numbers

[[1]]
 [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
[39] 138 139 140 141 142 143 144 145 146 147 148 149 150

In [43]:
lapply(numbers,mean)
sapply(numbers,mean)

lapply(numbers,sd)
sapply(numbers,sd)

[[1]]
[1] 125

[1] 125

[[1]]
[1] 14.86607

[1] 14.86607

In [44]:
## to apply the "apply" function, we need to convert the sequence into the matrix:
numbers <- matrix(c(101:150),nrow = 5,ncol = 10)
numbers

apply(numbers,1,mean)
apply(numbers,1,sd)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 101  106  111  116  121  126  131  136  141  146  
[2,] 102  107  112  117  122  127  132  137  142  147  
[3,] 103  108  113  118  123  128  133  138  143  148  
[4,] 104  109  114  119  124  129  134  139  144  149  
[5,] 105  110  115  120  125  130  135  140  145  150

[1] 123.5 124.5 125.5 126.5 127.5

[1] 15.13825 15.13825 15.13825 15.13825 15.13825

In [45]:
## to apply the "tapply" function, we need to create an index named "t":
t <- gl(2,25)
t

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2
[39] 2 2 2 2 2 2 2 2 2 2 2 2
Levels: 1 2

In [46]:
tapply(numbers,t,mean)
tapply(numbers,t,sd)

1   2 
113 138

1        2 
7.359801 7.359801

In [14]:
#### End solution ####

### Question 2
**Create a matrix of dimensions 4x4**
1. Find the row-wise and column-wise mean of the matrix.
2. Print the values.

In [9]:
#### Start solution ####

In [47]:
## Create a matrix of dimensions 4x4:
mtrx <- matrix(1:16,nrow = 4,ncol = 4)
mtrx

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [48]:
row_wise_mean <- apply(mtrx,1,mean)
column_wise_mean <- apply(mtrx,2,mean)

In [49]:
row_wise_mean
column_wise_mean

[1]  7  8  9 10

[1]  2.5  6.5 10.5 14.5

In [50]:
print(paste(row_wise_mean))

[1] "7"  "8"  "9"  "10"


In [51]:
print(paste(column_wise_mean))

[1] "2.5"  "6.5"  "10.5" "14.5"


In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 7: Data Split

### Question 1
**Using the data frame Orange:**
1. Using split function to break down the dataset on circumference and store it in 'split_data' variable. 
2. Print the values for split_data where circumference is 30 and 75.
3. Find the average age of the tree when the circumference is 30 and when circumference is 214.


The dataset is loaded and the variable Orange contains the respective dataset.

In [21]:
library(datasets)

In [25]:
head(Orange)

Tree age  circumference
1 1     118  30          
2 1     484  58          
3 1     664  87          
4 1    1004 115          
5 1    1231 120          
6 1    1372 142

In [9]:
#### Start solution ####

In [52]:
split_data <- split(Orange, Orange$circumference)
split_data

$`30`
   Tree age circumference
1     1 118            30
15    3 118            30
29    5 118            30

$`32`
   Tree age circumference
22    4 118            32

$`33`
  Tree age circumference
8    2 118            33

$`49`
   Tree age circumference
30    5 484            49

$`51`
   Tree age circumference
16    3 484            51

$`58`
  Tree age circumference
2    1 484            58

$`62`
   Tree age circumference
23    4 484            62

$`69`
  Tree age circumference
9    2 484            69

$`75`
   Tree age circumference
17    3 664            75

$`81`
   Tree age circumference
31    5 664            81

$`87`
  Tree age circumference
3    1 664            87

$`108`
   Tree  age circumference
18    3 1004           108

$`111`
   Tree age circumference
10    2 664           111

$`112`
   Tree age circumference
24    4 664           112

$`115`
   Tree  age circumference
4     1 1004           115
19    3 1231           115

$`120`
  Tree  age circumference
5    1 1231           120

$`125`
   Tree  age circumference
32    5 1004           125

$`139`
   Tree  age circumference
20    3 1372           139

$`140`
   Tree  age circumference
21    3 1582           140

$`142`
   Tree  age circumference
6     1 1372           142
33    5 1231           142

$`145`
  Tree  age circumference
7    1 1582           145

$`156`
   Tree  age circumference
11    2 1004           156

$`167`
   Tree  age circumference
25    4 1004           167

$`172`
   Tree  age circumference
12    2 1231           172

$`174`
   Tree  age circumference
34    5 1372           174

$`177`
   Tree  age circumference
35    5 1582           177

$`179`
   Tree  age circumference
26    4 1231           179

$`203`
   Tree  age circumference
13    2 1372           203
14    2 1582           203

$`209`
   Tree  age circumference
27    4 1372           209

$`214`
   Tree  age circumference
28    4 1582           214

In [53]:
split_data$"30"

Tree age circumference
1  1    118 30           
15 3    118 30           
29 5    118 30

In [54]:
split_data$"75"

Tree age circumference
17 3    664 75

In [55]:
a <- split_data[c("30","214")]
a

$`30`
   Tree age circumference
1     1 118            30
15    3 118            30
29    5 118            30

$`214`
   Tree  age circumference
28    4 1582           214

In [56]:
sapply(a, function(x) colMeans(x[,c("age","circumference")], na.rm = TRUE))

30  214 
age           118 1582
circumference  30  214

In [14]:
#### End solution ####


### Save it and push .ipynb and .html file to your Github Repository
## GOOD JOB! You have successfully finished the course!